// Fairphone-specific product data and reference information

export const FAIRPHONE_PRODUCTS = [
  {
    id: "fp5",
    name: "Fairphone 5",
    sku: "FP5",
    hsCode: "8517.62.20",
    eccn: "EAR99",
    riskLevel: "green",
    dualUse: false,
    suppliers: ["Key EMS partner (CN)", "US distribution partner"],
    components: [
      { name: "Snapdragon processor", origin: "US", eccn: "3A001" },
      { name: "Gorilla Glass screen", origin: "US", eccn: "EAR99" },
      { name: "Lithium battery", origin: "CN", hazmat: true },
      { name: "Camera module", origin: "JP", eccn: "EAR99" },
    ],
  },
  {
    id: "fp4",
    name: "Fairphone 4",
    sku: "FP4",
    hsCode: "8517.62.20",
    eccn: "EAR99",
    riskLevel: "green",
    dualUse: false,
    suppliers: ["Key EMS partner (CN)"],
    components: [
      { name: "Snapdragon processor", origin: "US", eccn: "3A001" },
      { name: "Camera module", origin: "JP", eccn: "EAR99" },
    ],
  },
  {
    id: "spare-parts",
    name: "Spare Parts & Modules",
    sku: "SPARE",
    hsCode: "8517.62.20",
    eccn: "varies",
    riskLevel: "yellow",
    dualUse: false,
    components: [
      { name: "Display module", origin: "Multiple", eccn: "EAR99" },
      { name: "Battery module", origin: "CN", hazmat: true },
      { name: "Fairphone Modules (camera, NFC, etc)", origin: "Multiple", eccn: "EAR99" },
    ],
  },
  {
    id: "accessories",
    name: "Accessories & Cases",
    sku: "ACC",
    hsCode: "4202.21.00",
    eccn: "EAR99",
    riskLevel: "green",
    dualUse: false,
  },
]

export const FAIRPHONE_SUPPLIERS = [
  {
    id: "sup-1",
    name: "Key EMS partner (CN)",
    country: "China",
    region: "CN → EU",
    screeningStatus: "clear",
    lastScreened: "2025-01-06",
    wwft: true,
    sanctions: "clear",
    volume: "45%",
  },
  {
    id: "sup-2",
    name: "Logistics hub operator",
    country: "Netherlands",
    region: "NL / DE",
    screeningStatus: "clear",
    lastScreened: "2025-01-10",
    wwft: true,
    sanctions: "clear",
    volume: "25%",
  },
  {
    id: "sup-3",
    name: "US distribution partner",
    country: "USA",
    region: "US",
    screeningStatus: "pending",
    lastScreened: "2024-12-06",
    wwft: true,
    sanctions: "clear",
    volume: "20%",
  },
  {
    id: "sup-4",
    name: "Raw material supplier",
    country: "Vietnam",
    region: "Multiple",
    screeningStatus: "hit",
    lastScreened: "2025-01-13",
    wwft: false,
    sanctions: "potential-match",
    volume: "10%",
  },
]

export const TRADE_ROUTES = [
  { origin: "CN", destination: "EU", flow: "Main manufacturing to sales", volume: "60%" },
  { origin: "CN", destination: "UK", flow: "Post-Brexit distributor", volume: "15%" },
  { origin: "CN", destination: "NO", flow: "Nordic distributor", volume: "8%" },
  { origin: "EU", destination: "EU", flow: "Repair & RMA hub (NL/DE)", volume: "10%" },
  { origin: "US", destination: "US", flow: "US expansion (pending)", volume: "5%" },
  { origin: "JP", destination: "JP", flow: "Spare parts supplier", volume: "2%" },
]

export const COMPLIANCE_FRAMEWORKS = [
  { name: "EU Dual-Use Regulation 2021/821", scope: "Export control, technology transfer" },
  { name: "US EAR (Export Administration Regulations)", scope: "US origin items, re-exports" },
  { name: "US OFAC Sanctions", scope: "Country restrictions, entity screening" },
  { name: "EU AML/WWFT", scope: "Customer due diligence, wire transfer restrictions" },
  { name: "Customs Regulations (HS/ECCN)", scope: "Classification, documentation" },
  { name: "ESG & Due Diligence", scope: "Supply chain transparency, grievance mechanism" },
]

export const ROLES_PERMISSIONS = {
  procurement: {
    label: "Procurement Manager",
    color: "blue",
    permissions: ["view-suppliers", "submit-new-suppliers", "view-products", "view-shipments", "view-documents"],
    responsibilities: [
      "Source suppliers",
      "Review screening results",
      "Approve purchase orders",
      "Track RFQs and contracts",
    ],
  },
  logistics: {
    label: "Logistics / Operations",
    color: "purple",
    permissions: [
      "view-suppliers",
      "view-products",
      "submit-shipments",
      "view-shipments",
      "view-documents",
      "view-customs",
    ],
    responsibilities: ["Plan shipments", "Prepare customs docs", "Track delivery status", "Manage RMA/repair flows"],
  },
  compliance: {
    label: "Compliance / Legal",
    color: "emerald",
    permissions: [
      "view-all",
      "submit-all",
      "approve-screening",
      "approve-classification",
      "release-shipments",
      "manage-documents",
      "generate-reports",
    ],
    responsibilities: [
      "Conduct due diligence",
      "Review screenings & classifications",
      "Approve shipments",
      "Manage audit evidence",
      "Escalate risks",
    ],
  },
  management: {
    label: "Management / Exec",
    color: "amber",
    permissions: ["view-overview", "view-reports", "view-kpis", "view-risks", "export-data"],
    responsibilities: [
      "Monitor KPIs",
      "Review executive summaries",
      "Approve high-risk decisions",
      "Ensure compliance culture",
    ],
  },
  "rsm-advisor": {
    label: "RSM Compliance Advisor",
    color: "rose",
    permissions: ["view-all", "submit-all", "generate-reports", "provide-guidance", "access-controls"],
    responsibilities: [
      "Guide implementation",
      "Review compliance controls",
      "Provide regulatory updates",
      "Support team training",
    ],
  },
}

export type RoleKey = keyof typeof ROLES_PERMISSIONS

export const PRODUCT_REGULATORY_MAPPING = {
  fp5: {
    productId: "fp5",
    name: "Fairphone 5",
    hsCode: "8517.62.20",
    regulatoryStatus: {
      euDualUse: { applicable: false, reason: "Consumer electronics, no military application" },
      euMilitaryList: { applicable: false },
      usDualUse: { applicable: true, reason: "Contains components subject to EAR" },
      itar: { applicable: false },
      dualUseItems: false,
      militaryTech: false,
      encryption: false,
    },
    componentsRisk: [
      {
        name: "Snapdragon processor",
        origin: "US",
        eccn: "3A001",
        risk: "potential",
        reason: "US origin item subject to re-export controls",
      },
      {
        name: "Gorilla Glass screen",
        origin: "US",
        eccn: "EAR99",
        risk: "low",
        reason: "Commodity item, no specific control",
      },
      {
        name: "Lithium battery",
        origin: "CN",
        risk: "medium",
        reason: "Hazmat, customs documentation required",
      },
    ],
    supplyChainRisks: [
      "China-US trade tensions affecting US component sourcing",
      "Potential re-export restrictions on US components to certain destinations",
      "Customs complexity for multi-origin assembly",
    ],
  },
  fp4: {
    productId: "fp4",
    name: "Fairphone 4",
    hsCode: "8517.62.20",
    regulatoryStatus: {
      euDualUse: { applicable: false },
      euMilitaryList: { applicable: false },
      usDualUse: { applicable: true },
      itar: { applicable: false },
      dualUseItems: false,
      militaryTech: false,
      encryption: false,
    },
    componentsRisk: [
      { name: "Snapdragon processor", origin: "US", eccn: "3A001", risk: "potential" },
      { name: "Camera module", origin: "JP", eccn: "EAR99", risk: "low" },
    ],
  },
}

export const SUPPLY_CHAIN_SCENARIOS = {
  baseline: {
    name: "Current Supply Chain (Baseline)",
    description: "CN → EU → Distribution",
    routes: [
      { origin: "CN", destination: "EU", volume: "60%", riskLevel: "medium", scenario: "baseline" },
      { origin: "CN", destination: "UK", volume: "15%", riskLevel: "medium", scenario: "baseline" },
      { origin: "CN", destination: "NO", volume: "8%", riskLevel: "medium", scenario: "baseline" },
    ],
    risks: ["China-US trade tensions", "Potential sanctions impact", "Supply concentration in China"],
    mitigations: ["Multi-source component strategy", "Logistics hub in EU"],
  },
  "us-expansion": {
    name: "US Market Expansion",
    description: "Add direct US manufacturing/distribution",
    routes: [
      { origin: "US", destination: "US", volume: "10%", riskLevel: "low", scenario: "us-expansion" },
      { origin: "CN", destination: "EU", volume: "50%", riskLevel: "medium", scenario: "us-expansion" },
    ],
    risks: [
      "ITAR/EAR compliance for US operations",
      "Technology transfer restrictions",
      "US vendor due diligence complexity",
    ],
    mitigations: ["US entity compliance program", "Supplier screening in US", "Dedicated US compliance officer"],
  },
  "taiwan-risk": {
    name: "Taiwan Crisis Scenario",
    description: "Semiconductor supply disruption",
    routes: [
      { origin: "SG", destination: "EU", volume: "30%", riskLevel: "high", scenario: "taiwan-risk" },
      { origin: "KR", destination: "EU", volume: "20%", riskLevel: "high", scenario: "taiwan-risk" },
      { origin: "CN", destination: "EU", volume: "20%", riskLevel: "high", scenario: "taiwan-risk" },
    ],
    risks: [
      "Severe semiconductor shortage",
      "Alternative sourcing with new sanctions risks",
      "Production delays and compliance gaps",
    ],
    mitigations: [
      "Pre-qualified alternative component suppliers",
      "Strategic inventory of critical components",
      "Design flexibility for components",
      "Scenario-based vendor qualification",
    ],
  },
  "eu-sanctions-escalation": {
    name: "EU Sanctions Escalation",
    description: "Extended sanctions programs affecting China operations",
    routes: [
      { origin: "CN", destination: "EU", volume: "40%", riskLevel: "high", scenario: "eu-sanctions" },
      { origin: "VN", destination: "EU", volume: "30%", riskLevel: "medium", scenario: "eu-sanctions" },
      { origin: "TH", destination: "EU", volume: "15%", riskLevel: "medium", scenario: "eu-sanctions" },
    ],
    risks: [
      "Extended entity screening requirements",
      "Transshipment route complications",
      "Supplier financial impact and viability",
    ],
    mitigations: [
      "Real-time sanctions list monitoring",
      "Enhanced due diligence on all CN suppliers",
      "Transshipment audit procedures",
      "Supplier financial health monitoring",
    ],
  },
}

export const FAIRPHONE_MARKETS = {
  eu: {
    name: "EU & EEA",
    countries: ["Netherlands", "Germany", "France", "Italy", "Spain", "Poland", "Austria", "Belgium"],
    volume: "60%",
    regulations: ["EU Dual-Use 2021/821", "EU AML/WWFT", "GDPR", "EU Tariff Code"],
    customs: "intra-EU",
    riskLevel: "low",
  },
  uk: {
    name: "United Kingdom",
    countries: ["UK"],
    volume: "15%",
    regulations: ["UK Export Control Order 2008", "UK OFAC equivalent", "UK AML"],
    customs: "post-Brexit",
    riskLevel: "medium",
  },
  ch: {
    name: "Switzerland/EFTA",
    countries: ["Switzerland", "Norway"],
    volume: "8%",
    regulations: ["Swiss export controls", "Swiss customs"],
    customs: "free trade agreement",
    riskLevel: "low",
  },
  us: {
    name: "United States (New 2025)",
    countries: ["USA - all states"],
    volume: "5%",
    regulations: ["US EAR", "US OFAC", "US tariffs"],
    customs: "transatlantic",
    riskLevel: "medium-high",
  },
  other: {
    name: "Limited Markets",
    countries: ["Colombia", "Ecuador", "Turkey"],
    volume: "12%",
    regulations: ["Country-specific export controls"],
    customs: "ad-hoc",
    riskLevel: "medium",
  },
}

export const FAIRPHONE_PRODUCTS_ENHANCED = [
  {
    id: "fp6",
    name: "Fairphone 6",
    sku: "FP6-256GB",
    release: "June 2025",
    specs:
      "Snapdragon 7s Gen 3, 8GB RAM, 256GB storage (expandable to 2TB), 6.31-inch OLED, 50MP cameras, IP55, 4415mAh",
    sustainability: "49% recycled materials, modular design, 7-year OS support, 8-year security patches",
    hsCode: "8517.62.10",
    eccn: "EAR99",
    dualUse: false,
    components: [
      { name: "Snapdragon 7s processor", origin: "US", eccn: "3A001", risk: "potential", supplier: "Qualcomm" },
      { name: "OLED Display", origin: "South Korea", eccn: "EAR99", risk: "low", supplier: "Samsung" },
      { name: "Lithium battery", origin: "China", eccn: "EAR99", hazmat: true, risk: "medium", supplier: "Hi-P" },
      { name: "Camera module", origin: "Japan/China", eccn: "EAR99", risk: "low", supplier: "Multiple" },
      { name: "Fairtrade gold connectors", origin: "Rwanda", eccn: "EAR99", risk: "low", supplier: "Fair Minerals" },
    ],
    markets: ["EU", "UK", "CH", "US", "Other"],
    certifications: ["iFixit 10/10", "TCO Certified", "Fair Trade Gold", "B Corp"],
  },
  {
    id: "fp5",
    name: "Fairphone 5",
    sku: "FP5-256GB",
    release: "August 2023",
    specs: "QCM6490, 6/8GB RAM, 6.46-inch OLED, 50MP main camera, IP55, 4200mAh",
    sustainability: "36% recycled, modular, 8 years OS support, 10 years security patches",
    hsCode: "8517.62.10",
    eccn: "EAR99",
    dualUse: false,
    components: [
      { name: "QCM6490 processor", origin: "China", eccn: "3A001", risk: "potential", supplier: "Qualcomm" },
      { name: "OLED Display", origin: "South Korea", eccn: "EAR99", risk: "low", supplier: "Samsung" },
      { name: "Lithium battery", origin: "China", eccn: "EAR99", hazmat: true, risk: "medium", supplier: "Hi-P" },
    ],
    markets: ["EU", "UK", "CH", "Other"],
    certifications: ["iFixit 10/10", "TCO Certified", "Fair Trade Gold"],
  },
  {
    id: "fp4",
    name: "Fairphone 4",
    sku: "FP4-128GB",
    release: "September 2021",
    specs: "Snapdragon 750G, 6GB RAM, 6.3-inch display, 48MP dual camera, 3905mAh",
    sustainability: "28% recycled, fairtrade gold/silver, 7-year security patches",
    hsCode: "8517.62.10",
    eccn: "EAR99",
    dualUse: false,
    components: [{ name: "Snapdragon 750G", origin: "US", eccn: "3A001", risk: "potential", supplier: "Qualcomm" }],
    markets: ["EU", "UK", "US (limited)", "Other"],
    certifications: ["TCO Certified", "Fair Trade Gold"],
  },
  {
    id: "fairbuds-xl",
    name: "Fairbuds XL",
    sku: "FAIRBUDS-XL",
    release: "2024",
    specs: "Over-ear wireless, ANC, 37-hour battery, IP54 rated",
    sustainability: "66% recycled materials, 5 replaceable parts, repairable design",
    hsCode: "8518.30.00",
    eccn: "EAR99",
    dualUse: false,
    components: [
      { name: "Bluetooth module", origin: "US", eccn: "EAR99", risk: "low", supplier: "Multiple" },
      { name: "Battery", origin: "China", eccn: "EAR99", hazmat: true, risk: "medium", supplier: "Hi-P" },
    ],
    markets: ["EU", "UK", "US", "CH"],
    certifications: ["B Corp", "Fair Trade"],
  },
  {
    id: "fairbuds",
    name: "Fairbuds",
    sku: "FAIRBUDS",
    release: "2023",
    specs: "True wireless earbuds, 32-hour battery, modular replaceable parts",
    sustainability: "49% recycled materials, 8 replaceable parts",
    hsCode: "8518.30.00",
    eccn: "EAR99",
    dualUse: false,
    markets: ["EU", "UK", "US", "CH"],
    certifications: ["B Corp"],
  },
  {
    id: "cases-chargers",
    name: "Cases & Chargers",
    sku: "ACC-VARIOUS",
    release: "Ongoing",
    specs: "Protective cases, USB-C chargers, cables",
    sustainability: "Recycled materials, repairable",
    hsCode: "4202.21.00",
    eccn: "EAR99",
    dualUse: false,
    markets: ["EU", "UK", "US", "CH", "Other"],
  },
  {
    id: "repair-parts",
    name: "Spare Parts & Modules",
    sku: "PARTS-VARIOUS",
    release: "Ongoing",
    specs: "Display modules, battery modules, camera modules, connectivity modules",
    sustainability: "Individual component replacement enables device longevity",
    hsCode: "varies",
    eccn: "varies",
    dualUse: false,
    riskLevel: "medium",
    components: [
      { name: "Display modules", origin: "Multiple", eccn: "EAR99", risk: "low" },
      { name: "Battery modules", origin: "China", eccn: "EAR99", hazmat: true, risk: "medium" },
      { name: "Camera modules", origin: "Japan", eccn: "EAR99", risk: "low" },
    ],
    markets: ["EU", "UK", "US", "CH", "Other"],
  },
]

export const FAIRPHONE_SUPPLIERS_ENHANCED = [
  {
    id: "sup-1",
    name: "Hi-P International Limited",
    country: "China",
    region: "Suzhou, CN",
    role: "Primary EMS/ODM partner",
    volume: "45%",
    products: ["FP6", "FP5", "FP4", "Batteries"],
    screeningStatus: "clear",
    lastScreened: "2025-01-06",
    wwft: true,
    sanctions: "clear",
    beneficialOwners: "Verified - Singapore listed",
    riskFactors: ["China-based manufacturing", "US component sourcing"],
    certifications: ["ISO 9001", "ISO 14001", "RoHS compliant"],
    wwftDocumented: true,
  },
  {
    id: "sup-2",
    name: "Fairphone B.V. Logistics Hub",
    country: "Netherlands",
    region: "Amsterdam, NL",
    role: "EU distribution & RMA center",
    volume: "25%",
    products: ["All products - distribution"],
    screeningStatus: "clear",
    lastScreened: "2025-01-10",
    wwft: true,
    sanctions: "clear",
    beneficialOwners: "Tessa Wernink, Bas van Abel (founders)",
    riskFactors: ["EU domiciled - low risk"],
    certifications: ["B Corp", "Tax compliant"],
    wwftDocumented: true,
  },
  {
    id: "sup-3",
    name: "T-Mobile/Murena (US Distribution)",
    country: "USA",
    region: "USA",
    role: "US carrier & distributor",
    volume: "5%",
    products: ["FP6", "Fairbuds XL"],
    screeningStatus: "pending",
    lastScreened: "2024-12-06",
    wwft: true,
    sanctions: "clear",
    beneficialOwners: "Major carriers - public companies",
    riskFactors: ["US expansion new", "Requires updated screening"],
    certifications: ["FCC compliant"],
    wwftDocumented: false,
  },
  {
    id: "sup-4",
    name: "Qualcomm Inc.",
    country: "USA",
    region: "San Diego, USA",
    role: "Processor manufacturer",
    volume: "component",
    products: ["Snapdragon processors - FP6, FP5, FP4"],
    screeningStatus: "clear",
    lastScreened: "2025-01-13",
    wwft: true,
    sanctions: "clear",
    beneficialOwners: "Publicly listed - NASDAQ QCOM",
    riskFactors: ["US origin subject to EAR", "Strategic technology"],
    certifications: ["SEC registered"],
    wwftDocumented: true,
  },
  {
    id: "sup-5",
    name: "Samsung Display",
    country: "South Korea",
    region: "South Korea",
    role: "OLED display supplier",
    volume: "component",
    products: ["OLED displays - FP6, FP5"],
    screeningStatus: "clear",
    lastScreened: "2025-01-08",
    wwft: true,
    sanctions: "clear",
    beneficialOwners: "Samsung Group - public",
    riskFactors: ["South Korea allied nation"],
    certifications: ["ISO 9001", "ISO 14001"],
    wwftDocumented: true,
  },
  {
    id: "sup-6",
    name: "Fair Minerals/Fairmined Gold Suppliers",
    country: "Rwanda/Peru",
    region: "Africa/South America",
    role: "Fair trade raw materials",
    volume: "component",
    products: ["Fairtrade gold - connectors"],
    screeningStatus: "clear",
    lastScreened: "2025-01-12",
    wwft: false,
    sanctions: "clear",
    beneficialOwners: "Cooperative structures",
    riskFactors: ["Higher-risk jurisdictions but ethical sourcing verified"],
    certifications: ["Fairmined Gold Certified", "Conflict-free verified"],
    wwftDocumented: false,
  },
]
